# Generated by Django 4.1.2 on 2022-10-16 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmodel',
            name='vid_dir',
            field=models.URLField(null=True),
        ),
    ]
